-- KhaataX — master schema. One file, one run, fresh project.
--
-- This is the CONSOLIDATED END STATE of migrations 0001..0010, not an eleventh
-- migration. It is for standing up a NEW Supabase project (production, staging, a
-- throwaway test project) in a single SQL Editor paste, without replaying ten
-- files and the three corrections among them.
--
--   * Do NOT run this against a project that already has 0001..0010 applied.
--     Run the numbered migrations there and keep running them.
--   * Do NOT edit this file in place when the schema changes. Write a new
--     numbered migration in `migrations/`, apply it, then fold it in here. The
--     numbered files remain the source of truth and the audit trail — this file
--     is a build artifact of them.
--
-- WHAT THE NUMBERED HISTORY CONTAINS THAT THIS FILE DOES NOT:
--
-- Three migrations exist to correct earlier ones, and their corrections are
-- simply the state below — the mistakes are not reproduced and then fixed:
--
--   0005 moved the app role off the reserved `role` JWT claim onto `app_role`
--        (0003 wrote `role`, which Supabase does not permit a hook to overwrite,
--        so every policy denied every user).
--   0007 moved the trust boundary from the sign-in screen to the table:
--        `transactions` / `stock` became read-only to clients, derived columns
--        lost their write grants, and the RPCs became `security definer`.
--   0010 reversed 0009's "this is not a receivables ledger" decision and made it
--        one, by adding payments.
--
-- Read `migrations/` for the reasoning behind any specific decision here. Read
-- `../README.md` for the post-run steps this file cannot perform.
--
-- AFTER RUNNING THIS, the project is NOT yet usable. You must still:
--   1. Enable the Custom Access Token Hook (Dashboard -> Authentication -> Hooks
--      -> Custom Access Token -> `public.custom_access_token_hook`). Without it
--      `app_role` never reaches the JWT and every policy denies everyone.
--   2. Create auth users and insert matching `public.users` rows with a role.
--   3. Sign out and back in — claims are stamped at token issue time.
--   4. Run `npm run test:rls` against the project before trusting it.
-- See ../README.md sections 3, 4 and 6 for the details.


begin;


-- =============================================================================
-- 1. Tables
-- =============================================================================
--
-- Per docs/TRD.md Section 3, with the columns added by 0009 (transactions.amount)
-- and 0010 (parties.amount_due, payments) folded in.
--
-- CHECK constraints that the numbered migrations had to add NOT VALID — because
-- they were retrofitted onto existing billing history — are plain, validated
-- constraints here. A new project has no history to exempt.

create table if not exists public.users (
  id            uuid primary key references auth.users,
  name          text not null,
  role          text not null check (role in ('owner','manager')),
  created_at    timestamptz default now()
);

-- TWO BALANCES, AND THEY ARE NOT INTERCHANGEABLE:
--   balance     = cylinders held by the party   (a COUNT)
--   amount_due  = rupees owed by the party      (MONEY)
-- Never render one where the other belongs. Both are derived: they move only
-- inside the SECURITY DEFINER functions below, and neither is in any client
-- grant. A negative `amount_due` is valid and means the party is in credit.
create table if not exists public.parties (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  contact            text,
  security_deposit   numeric not null default 0
                     constraint parties_deposit_non_negative check (security_deposit >= 0),
  balance            numeric not null default 0,
  amount_due         numeric(12,2) not null default 0,
  created_at         timestamptz default now()
);

-- Independent sequences. invoice_no and dc_no do not match and are not meant to;
-- both are assigned server-side inside create_transaction, never by a client
-- (CLAUDE.md Non-Negotiable Rule 2).
create sequence if not exists public.invoice_no_seq start 201;
create sequence if not exists public.dc_no_seq start 101;

create table if not exists public.transactions (
  id               uuid primary key default gen_random_uuid(),
  party_id         uuid not null references public.parties(id),
  date             date not null default current_date,
  invoice_no       integer not null unique,
  dc_no            integer not null unique,
  cylinder_type    text not null,
  filled_sent      integer not null default 0
                   constraint transactions_filled_sent_non_negative check (filled_sent >= 0),
  empty_received   integer not null default 0
                   constraint transactions_empty_received_non_negative check (empty_received >= 0),
  amount           numeric(12,2) not null default 0
                   constraint transactions_amount_non_negative check (amount >= 0),
  -- Stamped by the DEFAULT, never asserted by the client — the column carries no
  -- INSERT grant, so attribution cannot be forged.
  created_by       uuid not null references public.users(id) default auth.uid(),
  created_at       timestamptz default now(),
  constraint transactions_movement_non_empty check (filled_sent + empty_received > 0)
);

create table if not exists public.stock (
  status      text primary key check (status in
              ('filled','empty','at_customer','under_refill','damaged')),
  quantity    integer not null default 0
              constraint stock_quantity_non_negative check (quantity >= 0),
  updated_at  timestamptz default now()
);

insert into public.stock (status, quantity) values
  ('filled', 0),
  ('empty', 0),
  ('at_customer', 0),
  ('under_refill', 0),
  ('damaged', 0)
on conflict (status) do nothing;

create table if not exists public.expenses (
  id           uuid primary key default gen_random_uuid(),
  date         date not null default current_date,
  amount       numeric not null check (amount > 0),
  category     text not null,
  note         text,
  created_by   uuid not null references public.users(id) default auth.uid(),
  created_at   timestamptz default now()
);

-- The only table restricted to the owner role (Non-Negotiable Rule 1).
create table if not exists public.employees (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  role          text,
  monthly_pay   numeric not null check (monthly_pay >= 0),
  active        boolean not null default true,
  created_at    timestamptz default now()
);

-- Money received, recorded against the PARTY — not matched to an invoice. There
-- is no allocation, no partial-invoice settlement, no aging of money.
-- Immutable by design: no UPDATE path exists. A mis-keyed payment is removed via
-- delete_payment (which returns the money to amount_due in the same database
-- transaction) and re-recorded.
create table if not exists public.payments (
  id           uuid primary key default gen_random_uuid(),
  party_id     uuid not null references public.parties(id),
  date         date not null default current_date,
  -- amount > 0: a payment is money IN. A negative "payment" is a charge, and
  -- charges belong on a transaction, where they get an invoice number.
  amount       numeric(12,2) not null check (amount > 0),
  method       text not null default 'cash'
               check (method in ('cash','upi','bank','cheque','other')),
  note         text,
  created_by   uuid not null references public.users(id) default auth.uid(),
  created_at   timestamptz default now()
);


-- =============================================================================
-- 2. Indexes
-- =============================================================================
--
-- The only repeated range scans in the app: the expense dashboard (today / MTD /
-- YTD / 12-month trend), the Outstanding Report walking a party's transactions
-- in date order, and the party payment history.

create index if not exists expenses_date_idx on public.expenses (date desc);
create index if not exists expenses_category_idx on public.expenses (category);
create index if not exists expenses_created_by_idx on public.expenses (created_by);
create index if not exists transactions_party_date_idx on public.transactions (party_id, date);
create index if not exists payments_party_date_idx on public.payments (party_id, date desc);


-- =============================================================================
-- 3. Custom Access Token Hook
-- =============================================================================
--
-- Projects `public.users.role` onto the JWT as `app_role`, which every policy
-- below reads.
--
-- `app_role`, NOT `role`: `role` is reserved by Supabase Auth for the Postgres
-- role PostgREST switches to (`authenticated` / `anon`). A hook may not overwrite
-- it, and if it could, PostgREST would then attempt `SET ROLE owner` against a
-- role that does not exist. 0003 made that mistake and 0005 corrected it.
--
-- `set search_path = ''` because this runs as `supabase_auth_admin`, one of the
-- most privileged roles in the project; unqualified name resolution there is a
-- standing escalation risk.

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $func$
declare
  claims jsonb;
  user_role text;
begin
  select role into user_role from public.users where id = (event->>'user_id')::uuid;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{app_role}', to_jsonb(user_role));
  end if;

  return jsonb_build_object('claims', claims);
end;
$func$;

grant usage on schema public to supabase_auth_admin;
grant select on table public.users to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;


-- =============================================================================
-- 4. Row-Level Security
-- =============================================================================
--
-- Every policy is scoped `to authenticated`. Anonymous callers would be denied
-- anyway (the claim is NULL, and `NULL in (...)` is never true), but scoping
-- means the policy is not evaluated for anon at all, and states the intent.

alter table public.users        enable row level security;
alter table public.parties      enable row level security;
alter table public.transactions enable row level security;
alter table public.stock        enable row level security;
alter table public.expenses     enable row level security;
alter table public.employees    enable row level security;
alter table public.payments     enable row level security;

-- users -----------------------------------------------------------------------
--
-- read_own_user keys off auth.uid() rather than the role claim, which is why it
-- kept working during the 0003/0005 claim outage while everything else denied.

drop policy if exists "read_own_user" on public.users;
create policy "read_own_user" on public.users
  for select using (id = auth.uid());

-- Staff directory. `users` holds only id, name and role — no pay, no contact
-- details. Compensation lives in `employees`, which managers cannot see at all,
-- so this does not touch the payroll boundary. SELECT only.
drop policy if exists "read_all_users" on public.users;
create policy "read_all_users" on public.users
  for select to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'));

-- The hook runs as `supabase_auth_admin`, which is itself subject to RLS on this
-- table — a table GRANT does not exempt a role from RLS. Without this policy the
-- hook's role lookup returns NULL and it silently attaches no claim: sign-in
-- works, the token looks normal, and every role-based policy denies everyone.
-- `read_own_user` cannot serve (auth.uid() is NULL inside the hook) and
-- `read_all_users` cannot either (it needs the very claim being produced).
drop policy if exists "auth_admin_can_read_user_roles" on public.users;
create policy "auth_admin_can_read_user_roles" on public.users
  as permissive
  for select
  to supabase_auth_admin
  using (true);

-- parties ---------------------------------------------------------------------
--
-- Fully writable by both roles at the ROW level. The derived columns (`balance`,
-- `amount_due`) are excluded at the GRANT level in section 6 instead, because a
-- policy can restrict which rows an UPDATE touches but not which columns.

drop policy if exists "owner_and_manager_full_access" on public.parties;
create policy "owner_and_manager_full_access" on public.parties
  for all to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'))
  with check (auth.jwt() ->> 'app_role' in ('owner', 'manager'));

-- transactions ----------------------------------------------------------------
--
-- Readable only. No INSERT/UPDATE/DELETE policy exists, so all three are denied
-- by default; writes go through create_transaction.

drop policy if exists "read_transactions" on public.transactions;
create policy "read_transactions" on public.transactions
  for select to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'));

-- stock -----------------------------------------------------------------------
--
-- Readable only; writes go through adjust_stock / create_transaction.

drop policy if exists "read_stock" on public.stock;
create policy "read_stock" on public.stock
  for select to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'));

-- expenses --------------------------------------------------------------------
--
-- Insert as yourself; edit and delete only your own. This NARROWS CLAUDE.md's
-- "both roles have full read/write" for this one table, deliberately: attribution
-- is worthless if any manager can rewrite another user's expense, and the TRD
-- lists created_by as the auditability control. Reads stay unrestricted (the
-- dashboards aggregate across everyone) and the owner keeps full write access, so
-- no PRD story regresses — EXP-1..EXP-5 only ever create and read.

drop policy if exists "read_expenses" on public.expenses;
create policy "read_expenses" on public.expenses
  for select to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'));

drop policy if exists "insert_own_expenses" on public.expenses;
create policy "insert_own_expenses" on public.expenses
  for insert to authenticated
  with check (
    auth.jwt() ->> 'app_role' in ('owner', 'manager')
    and created_by = auth.uid()
  );

drop policy if exists "modify_own_expenses" on public.expenses;
create policy "modify_own_expenses" on public.expenses
  for update to authenticated
  using (created_by = auth.uid() or auth.jwt() ->> 'app_role' = 'owner')
  with check (created_by = auth.uid() or auth.jwt() ->> 'app_role' = 'owner');

drop policy if exists "delete_own_expenses" on public.expenses;
create policy "delete_own_expenses" on public.expenses
  for delete to authenticated
  using (created_by = auth.uid() or auth.jwt() ->> 'app_role' = 'owner');

-- employees -------------------------------------------------------------------
--
-- Owner only. There is deliberately NO policy for 'manager' — under RLS the
-- absence of a matching policy denies all access. This is Non-Negotiable Rule 1
-- and is proven by tests/rls-employees.test.ts, not by hiding the screen.

drop policy if exists "owner_full_access" on public.employees;
create policy "owner_full_access" on public.employees
  for all to authenticated
  using (auth.jwt() ->> 'app_role' = 'owner')
  with check (auth.jwt() ->> 'app_role' = 'owner');

-- payments --------------------------------------------------------------------
--
-- Same shape as transactions: readable, writable only through the RPCs.

drop policy if exists "read_payments" on public.payments;
create policy "read_payments" on public.payments
  for select to authenticated
  using (auth.jwt() ->> 'app_role' in ('owner', 'manager'));


-- =============================================================================
-- 5. Functions
-- =============================================================================
--
-- All four are SECURITY DEFINER with `set search_path = ''`.
--
-- DEFINER because section 6 removes the client write grants these functions need
-- — an invoker-rights function could no longer do its job. The authorisation
-- that RLS used to perform is therefore made explicit as the first statement in
-- each body, before any state is touched.
--
-- Empty search_path prevents a search-path hijack of the unqualified names a
-- definer function would otherwise resolve as its owner (postgres). Every
-- reference below is schema-qualified as a result; pg_catalog is still implicitly
-- searched, so built-in operators need no qualification.
--
-- SQLSTATE convention:
--   42501  not authorised
--   KX001  a message deliberately written FOR THE USER — src/lib/errors.ts keys
--          on this and passes it to the screen. Everything else gets generic
--          fallback text. (Not P0001: that is the default for *any* bare
--          `raise exception` in the database, ours or not, so keying on it
--          leaked arbitrary internal text to the UI.)

-- create_transaction ----------------------------------------------------------
--
-- The single atomic write for New Transaction: the transaction insert, both party
-- balances, and the stock movement happen together or not at all
-- (Non-Negotiable Rule 3). It is the ONLY write path into `transactions`.
--
-- Two details that are easy to lose in a rewrite:
--
--   * ALL validation runs before the first nextval(). Sequences are
--     non-transactional, so a failure after nextval() burns an invoice number
--     permanently, leaving a gap in a legally-sequenced series that no rollback
--     can close.
--   * The filled-stock read takes FOR UPDATE, and treats a MISSING row as
--     insufficient. Without the lock, two concurrent callers both pass the
--     sufficiency check and both decrement. Without the NULL check,
--     `NULL < p_filled_sent` is NULL — not false — so the guard falls through
--     and the write proceeds against stock that does not exist.

create or replace function public.create_transaction(
  p_party_id uuid,
  p_date date,
  p_cylinder_type text,
  p_filled_sent integer,
  p_empty_received integer,
  p_amount numeric
)
returns public.transactions
language plpgsql
security definer
set search_path = ''
as $func$
declare
  v_invoice_no integer;
  v_dc_no integer;
  v_transaction public.transactions;
  v_filled_available integer;
  v_amount numeric(12,2);
begin
  if auth.jwt() ->> 'app_role' not in ('owner', 'manager') then
    raise exception 'Not authorised to record transactions'
      using errcode = '42501';
  end if;

  if p_filled_sent is null or p_empty_received is null then
    raise exception 'Quantities are required' using errcode = 'KX001';
  end if;

  if p_filled_sent < 0 or p_empty_received < 0 then
    raise exception 'Quantities must be zero or more' using errcode = 'KX001';
  end if;

  if p_filled_sent + p_empty_received = 0 then
    raise exception 'A transaction must move at least one cylinder' using errcode = 'KX001';
  end if;

  if p_cylinder_type is null or btrim(p_cylinder_type) = '' then
    raise exception 'Cylinder type is required' using errcode = 'KX001';
  end if;

  if p_date is null then
    raise exception 'Date is required' using errcode = 'KX001';
  end if;

  -- NULL is rejected rather than coerced to 0: a client that forgot the field
  -- would otherwise silently record a free delivery, and the figure ends up on a
  -- document the party is handed.
  if p_amount is null then
    raise exception 'Amount charged is required' using errcode = 'KX001';
  end if;

  if p_amount < 0 then
    raise exception 'Amount charged cannot be negative' using errcode = 'KX001';
  end if;

  -- Rounded here, not left to the column cast, so what the RPC returns to the app
  -- is exactly what was stored.
  v_amount := round(p_amount, 2);

  if not exists (select 1 from public.parties where id = p_party_id) then
    -- No %: the id is an internal identifier, and this reaches the screen.
    raise exception 'That party no longer exists. Refresh and try again.'
      using errcode = 'KX001';
  end if;

  select quantity into v_filled_available
  from public.stock
  where status = 'filled'
  for update;

  if v_filled_available is null or v_filled_available < p_filled_sent then
    raise exception 'Only % filled cylinder(s) in stock, cannot send %',
      coalesce(v_filled_available, 0), p_filled_sent
      using errcode = 'KX001';
  end if;

  v_invoice_no := nextval('public.invoice_no_seq');
  v_dc_no := nextval('public.dc_no_seq');

  insert into public.transactions (
    party_id, date, invoice_no, dc_no, cylinder_type,
    filled_sent, empty_received, amount, created_by
  ) values (
    p_party_id, p_date, v_invoice_no, v_dc_no, btrim(p_cylinder_type),
    p_filled_sent, p_empty_received, v_amount, auth.uid()
  )
  returning * into v_transaction;

  -- One statement, both balances: the cylinder count and the money owed move
  -- together or not at all.
  update public.parties
  set balance    = balance + p_filled_sent - p_empty_received,
      amount_due = amount_due + v_amount
  where id = p_party_id;

  update public.stock set quantity = quantity - p_filled_sent, updated_at = now() where status = 'filled';
  update public.stock set quantity = quantity + p_filled_sent, updated_at = now() where status = 'at_customer';
  update public.stock set quantity = quantity + p_empty_received, updated_at = now() where status = 'empty';
  update public.stock set quantity = greatest(0, quantity - p_empty_received), updated_at = now() where status = 'at_customer';

  return v_transaction;
end;
$func$;

revoke execute on function public.create_transaction(uuid, date, text, integer, integer, numeric) from public, anon;
grant execute on function public.create_transaction(uuid, date, text, integer, integer, numeric) to authenticated;

-- adjust_stock ----------------------------------------------------------------
--
-- The client used to read the current quantity out of React state, add the delta
-- locally, and write an absolute value back — so two managers adjusting at once,
-- or one on a stale screen, silently overwrote each other. Doing the arithmetic
-- in a single UPDATE closes the window; that statement is already atomic, so it
-- needs no explicit lock.

create or replace function public.adjust_stock(
  p_status text,
  p_delta integer
)
returns public.stock
language plpgsql
security definer
set search_path = ''
as $func$
declare
  v_row public.stock;
begin
  if auth.jwt() ->> 'app_role' not in ('owner', 'manager') then
    raise exception 'Not authorised to adjust stock'
      using errcode = '42501';
  end if;

  if p_delta is null or p_delta = 0 then
    raise exception 'Adjustment amount is required' using errcode = 'KX001';
  end if;

  update public.stock
  set quantity = greatest(0, quantity + p_delta), updated_at = now()
  where status = p_status
  returning * into v_row;

  if not found then
    raise exception 'Unknown stock status %', p_status using errcode = 'KX001';
  end if;

  return v_row;
end;
$func$;

revoke execute on function public.adjust_stock(text, integer) from public, anon;
grant execute on function public.adjust_stock(text, integer) to authenticated;

-- record_payment --------------------------------------------------------------
--
-- The other half of the ledger. A sum of amounts charged only ever grows, so
-- "owes" is meaningless without a way to record money coming back in:
--
--   amount_due = sum(transactions.amount) - sum(payments.amount)
--
-- FOR UPDATE on the party row serialises concurrent payments against the same
-- party. Without it, two managers recording ₹5,000 each could both read the same
-- amount_due and both write `read - 5000`, losing one payment from the balance
-- while both rows sat in the table — the classic lost update, on money.
--
-- An overpayment is allowed through: amount_due goes negative and the party is in
-- credit. Advances are ordinary in this business, and rejecting them would push
-- the user into recording a fake charge to balance the books.

create or replace function public.record_payment(
  p_party_id uuid,
  p_date date,
  p_amount numeric,
  p_method text,
  p_note text
)
returns public.payments
language plpgsql
security definer
set search_path = ''
as $func$
declare
  v_payment public.payments;
  v_amount numeric(12,2);
  v_method text;
begin
  if auth.jwt() ->> 'app_role' not in ('owner', 'manager') then
    raise exception 'Not authorised to record payments'
      using errcode = '42501';
  end if;

  if p_amount is null then
    raise exception 'Payment amount is required' using errcode = 'KX001';
  end if;

  v_amount := round(p_amount, 2);

  -- Checked after rounding: 0.004 is not a payment, and rounding it first stops a
  -- row that satisfies this guard from failing the column CHECK a line later.
  if v_amount <= 0 then
    raise exception 'A payment must be more than zero' using errcode = 'KX001';
  end if;

  if p_date is null then
    raise exception 'Date is required' using errcode = 'KX001';
  end if;

  v_method := coalesce(nullif(btrim(lower(p_method)), ''), 'cash');
  if v_method not in ('cash','upi','bank','cheque','other') then
    raise exception 'Unknown payment method' using errcode = 'KX001';
  end if;

  perform 1 from public.parties where id = p_party_id for update;
  if not found then
    raise exception 'That party no longer exists. Refresh and try again.'
      using errcode = 'KX001';
  end if;

  insert into public.payments (party_id, date, amount, method, note, created_by)
  values (p_party_id, p_date, v_amount, v_method, nullif(btrim(p_note), ''), auth.uid())
  returning * into v_payment;

  update public.parties
  set amount_due = amount_due - v_amount
  where id = p_party_id;

  return v_payment;
end;
$func$;

revoke execute on function public.record_payment(uuid, date, numeric, text, text) from public, anon;
grant execute on function public.record_payment(uuid, date, numeric, text, text) to authenticated;

-- delete_payment --------------------------------------------------------------
--
-- The correction path. Deleting must put the money back on amount_due, which is
-- exactly why this is an RPC and not a DELETE grant: a plain delete would drop
-- the row and leave the cached balance overstating what was received, with
-- nothing to notice it.
--
-- Scoped to whoever recorded it, plus the owner — the same rule expenses use, for
-- the same reason.

create or replace function public.delete_payment(p_payment_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $func$
declare
  v_payment public.payments;
begin
  if auth.jwt() ->> 'app_role' not in ('owner', 'manager') then
    raise exception 'Not authorised to remove payments'
      using errcode = '42501';
  end if;

  select * into v_payment from public.payments where id = p_payment_id for update;

  if not found then
    raise exception 'That payment has already been removed.' using errcode = 'KX001';
  end if;

  if v_payment.created_by <> auth.uid() and auth.jwt() ->> 'app_role' <> 'owner' then
    raise exception 'Only the person who recorded a payment can remove it'
      using errcode = '42501';
  end if;

  delete from public.payments where id = p_payment_id;

  update public.parties
  set amount_due = amount_due + v_payment.amount
  where id = v_payment.party_id;
end;
$func$;

revoke execute on function public.delete_payment(uuid) from public, anon;
grant execute on function public.delete_payment(uuid) to authenticated;


-- =============================================================================
-- 6. Grants
-- =============================================================================
--
-- RLS decides which ROWS you may touch; it cannot decide which COLUMNS. Derived
-- and identifying columns are therefore kept out of the table-level grant.
--
-- Supabase grants `authenticated` and `anon` broad table privileges by default on
-- anything created in `public`, so these REVOKEs are load-bearing, not belt-and-
-- braces. A table-level privilege implies every column, and revoking a single
-- column while the table-level grant stands has no effect — hence revoke the
-- whole privilege first, then re-grant column by column.

-- Start from a known state rather than from whatever the defaults left behind.
revoke all on public.users, public.parties, public.transactions, public.stock,
              public.expenses, public.employees, public.payments
  from authenticated, anon;

-- users: read-only to clients. No client writes to this table at all — accounts
-- are provisioned by the developer (CLAUDE.md: there is no in-app user
-- management, do not build one).
grant select on public.users to authenticated;

-- parties: `balance` and `amount_due` are derived and appear in NEITHER the
-- INSERT nor the UPDATE grant, so they are unsettable at creation time as well as
-- afterwards. The granted columns are exactly PartyInput in src/types/db.ts.
grant select, delete on public.parties to authenticated;
grant insert (name, contact, security_deposit) on public.parties to authenticated;
grant update (name, contact, security_deposit) on public.parties to authenticated;

-- transactions / stock / payments: read-only. Writes go through the RPCs above.
grant select on public.transactions to authenticated;
grant select on public.stock to authenticated;
grant select on public.payments to authenticated;

-- expenses: `created_by` is stamped by the column DEFAULT and is not in the
-- grant, so attribution cannot be forged. DELETE is row-scoped by policy.
grant select, delete on public.expenses to authenticated;
grant insert (date, amount, category, note) on public.expenses to authenticated;
grant update (date, amount, category, note) on public.expenses to authenticated;

-- employees: full table privileges; the owner-only boundary is the RLS policy,
-- and the absence of any manager policy is what denies managers.
grant select, insert, update, delete on public.employees to authenticated;

-- anon has no business with any of this. Covered by the revoke above; restated
-- because it is the one line worth grepping for.
revoke all on public.parties, public.expenses, public.transactions,
              public.stock, public.employees, public.users, public.payments
  from anon;


commit;


-- =============================================================================
-- Verification
-- =============================================================================
--
-- Run these after the migration, and again after completing steps 1-3 in the
-- header. `npm run test:rls` is the real check — this is the by-hand version.
--
--   -- The hook can see roles (0 rows means the auth_admin policy is missing):
--   set role supabase_auth_admin;
--   select id, role from public.users limit 5;
--   reset role;
--
--   -- Signed in, this must print 'owner' or 'manager' — NOT 'authenticated':
--   select auth.jwt() ->> 'app_role';
--
--   -- As a manager, this must return zero rows (Non-Negotiable Rule 1):
--   select * from public.employees;
--
--   -- The cached amount_due agrees with its sources (zero rows = reconciled):
--   select p.id, p.name, p.amount_due
--   from public.parties p
--   where p.amount_due <> coalesce((select sum(t.amount) from public.transactions t
--                                   where t.party_id = p.id), 0)
--                       - coalesce((select sum(pay.amount) from public.payments pay
--                                   where pay.party_id = p.id), 0);
